### ISSUE TITLE
newest releases missing

### ISSUE THREAD

**Issue by knaeckeKami** [leoafarias/flutter_flat_data#3]
Hi,
is seems that the data is currently stable. The current stable, 2.2.2 ist still missing.
This also affects fvm.

See the current state of 
https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json
vs 
https://raw.githubusercontent.com/leoafarias/flutter_flat_data/main/releases_macos.json

**Comment by leoafarias** [comment]
The workflow is setup to run only once daily. The fvm should only be using this link as a fallback, so it should not impact it.

Did you find an issue with FVM?

**Comment by knaeckeKami** [comment]
Ah ok, I skimmed though the code of fvm and assumed this was where fvm would get the data for the releases.

Should I file an issue in the fvm repo?

**Comment by leoafarias** [comment]
No need, this is interesting the URL you have is different.

This is what I use:
https://storage.googleapis.com/flutter_infra/releases/releases_macos.json

This is yours:
https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json

It seems the repo does have the latest correct state… I am wonder why there are 2 different ones.

**Comment by knaeckeKami** [comment]
I copied the URL by inspecting the flutter releases webpage:
https://flutter.dev/docs/development/tools/sdk/releases?tab=linux

Maybe they updated the URL a few days ago?

**Comment by leoafarias** [comment]
Updated the URL here, and have updated also on FVM, and will be deploying a new version

**Comment by leoafarias** [comment]
Thank you for reporting it
